=== tigattack/VeeamNotify/config/conf.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "services": {
            "type": "object",
            "properties": {
                "discord": {
                    "type": "object",
                    "properties": {
                        "webhook": {
                            "type": "string"
                        },
                        "user_id": {
                            "type": "string"
                        }
                    }
                },
                "slack": {
                    "type": "object",
                    "properties": {
                        "webhook": {
                            "type": "string"
                        },
                        "user_id": {
                            "type": "string"
                        }
                    }
                },
                "teams": {
                    "type": "object",
                    "properties": {
                        "webhook": {
                            "type": "string"
                        },
                        "user_id": {
                            "type": "string"
                        },
                        "user_name": {
                            "type": "string"
                        }
                    }
                },
                "telegram": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string"
                        },
                        "chat_id": {
                            "type": "string"
                        }
                    }
                }
            },
            "required": [
                "discord",
                "slack",
                "teams",
                "telegram"
            ]
        },
        "mentions": {
            "type": "object",
            "properties": {
                "on_failure": {
                    "type": "boolean"
                },
                "on_warning": {
                    "type": "boolean"
                }
            }
        },
        "notifications": {
            "type": "object",
            "properties": {
                "on_success": {
                    "type": "boolean"
                },
                "on_failure": {
                    "type": "boolean"
                },
                "on_warning": {
                    "type": "boolean"
                }
            }
        },
        "logging": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "level": {
                    "type": "string"
                },
                "max_age_days": {
                    "type": "integer"
                }
            },
            "required": [
                "enabled",
                "level",
                "max_age_days"
            ]
        },
        "update": {
            "type": "object",
            "properties": {
                "notify": {
                    "type": "boolean"
                },
                "auto_update": {
                    "type": "boolean"
                },
                "auto_update_comment": {
                    "type": "string"
                }
            }
        },
        "thumbnail": {
            "type": "string"
        }
    },
    "required": [
        "services",
        "logging",
        "thumbnail"
    ]
}

=== tigattack/VeeamNotify/config/conf.json
{
    "services": {
        "discord": {
            "webhook": "DiscordWebhook",
            "user_id": "123456789"
        },
        "slack": {
            "webhook": "SlackWebhook",
            "user_id": "A1B2C3D4E5"
        },
        "teams": {
            "webhook": "TeamsWebhook",
            "user_id": "user@domain.tld",
            "user_name": "Your Name"
        },
        "telegram": {
            "token": "",
            "chat_id": ""
        }
    },
    "mentions": {
        "on_failure": false,
        "on_warning": false
    },
    "notifications": {
        "on_success": true,
        "on_failure": true,
        "on_warning": true
    },
    "logging": {
        "enabled": true,
        "level": "info",
        "max_age_days": 7
    },
    "update": {
        "notify": true,
        "auto_update": false,
        "auto_update_comment": "auto_update will NOT work. Leave as 'false'"
    },
    "thumbnail": "https://raw.githubusercontent.com/tigattack/VeeamDiscordNotifications/master/asset/thumb01.png"
}

=== tigattack/VeeamNotify/config/conf.example.json
{
    "services": {
        "discord": {
            "enabled": false,
            "webhook": "DiscordWebhook",
            "user_id": "123456789"
        },
        "slack": {
            "enabled": false,
            "webhook": "SlackWebhook",
            "user_id": "A1B2C3D4E5"
        },
        "teams": {
            "enabled": false,
            "webhook": "TeamsWebhook",
            "user_id": "user@domain.tld",
            "display_name": "Your Name"
        },
        "telegram": {
            "enabled": false,
            "bot_token": "TelegramBotToken",
            "chat_id": "TelegramChatID",
            "user_name": "yourusername"
        },
        "http": {
            "enabled": false,
            "url": "EndpointURL",
            "method": "POST"
        }
    },
    "mentions": {
        "on_failure": false,
        "on_warning": false,
        "on_success": false
    },
    "notifications": {
        "on_success": true,
        "on_failure": true,
        "on_warning": true
    },
    "logging": {
        "enabled": true,
        "level": "info",
        "max_age_days": 7
    },
    "update": {
        "notify": true,
        "auto_update": false,
        "auto_update_comment": "auto_update is not yet implemented. This will do nothing even if 'true'."
    },
    "thumbnail": "https://raw.githubusercontent.com/tigattack/VeeamNotify/main/asset/thumb01.png"
}
